<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>start_robot_package</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="arianke@kth.se">rosuser</maintainer>
  <license>MIT</license>

<!-- Custom interfaces -->
  <!-- <exec_depend>bing_interfaces</exec_depend> -->
  <depend>bing_interfaces</depend>
 


  <exec_depend>controller</exec_depend>
  <exec_depend>usb_cam</exec_depend>
  <exec_depend>aruco_ros</exec_depend>
  <exec_depend>builtin_interfaces</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>realsense2_camera</exec_depend>
  <exec_depend>realsense2_description</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>ros2launch</exec_depend>
  <exec_depend>robp_phidgets_encoders</exec_depend>
  <exec_depend>robp_phidgets_motors</exec_depend>
  <exec_depend>robp_phidgets_spatial</exec_depend>
  <exec_depend>robp_phidgets_temperature</exec_depend>
  <exec_depend>rplidar_ros</exec_depend>
  
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
